{{
    config(
        schema='bift',
        materialized='view',
        alias='v_oa_performance'
    )
}}

-- STREAM A: Passive Outlets Snapshot / Master Active CB Outlets (is_transaction = 0)
SELECT 
    cb.source_schema,
    cb.tahun,
    cb.periode,
    0::numeric                            AS week,
    NULL::date                            AS date,
    NULL::date                            AS inv_date,
    cb.gdiv_id,
    cb.gdiv_nm,
    cb.sd_id,
    cb.sd_nm,
    cb.nsm_id,
    cb.nsm_nm,
    cb.grsm_id,
    cb.grsm_nm,
    cb.rsm_id,
    cb.rsm_nm,
    cb.ss_id,
    cb.ss_nm,
    cb.distributor_id,
    cb.distributor_nm,
    cb.sls_id,
    cb.sls_nm,
    cb.gsalesforce1_id,
    cb.gsalesforce1_nm,
    cb.gsalesforce2_id,
    cb.gsalesforce2_nm,
    cb.salesforce_id,
    cb.salesforce_nm,
    cb.salesforce_div_id,
    cb.salesforce_div_nm,
    cb.team_id,
    cb.opr_type,
    cb.cust_id,
    cb.cust_nm,
    cb.channel_id,
    cb.channel_nm,
    cb.group_channel_id,
    cb.group_channel_nm,
    cb.cycle_kunjungan,
    cb.route,
    cb.provinsi_code,
    cb.provinsi_name,
    cb.kabupaten_code,
    cb.kabupaten_name,
    cb.kecamatan_code,
    cb.kecamatan_name,
    cb.kelurahan_code,
    cb.kelurahan_name,
    cb.latitude,
    cb.longitude,
    ''::varchar                           AS inv_no,
    ''::varchar                           AS pcode,
    ''::varchar                           AS pcode_nm,
    0::numeric                            AS inv_qty,
    0::numeric                            AS inv_val,
    0::numeric                            AS qty_carton,
    ''::varchar                           AS product_gdiv_id,
    ''::varchar                           AS product_gdiv_nm,
    ''::varchar                           AS div_id,
    ''::varchar                           AS div_nm,
    ''::varchar                           AS product_team_id,
    ''::varchar                           AS product_team_nm,
    ''::varchar                           AS class_team_id,
    ''::varchar                           AS class_team_nm,
    ''::varchar                           AS subbrand_id,
    ''::varchar                           AS subbrand_nm,
    ''::varchar                           AS cat_id,
    ''::varchar                           AS cat_nm,
    ''::varchar                           AS sbu_id,
    ''::varchar                           AS sbu_nm,
    0                                     AS is_transaction
FROM {{ ref('bronze_cb') }} cb

UNION ALL

-- STREAM B: Purchasing Outlets Sales Transactions (is_transaction = 1)
SELECT 
    t.source_schema,
    t.tahun,
    t.periode,
    t.week,
    t.date,
    t.inv_date,
    t.gdiv_id,
    t.gdiv_nm,
    t.sd_id,
    t.sd_nm,
    t.nsm_id,
    t.nsm_nm,
    t.grsm_id,
    t.grsm_nm,
    t.rsm_id,
    t.rsm_nm,
    t.ss_id,
    t.ss_nm,
    t.distributor_id,
    t.distributor_nm,
    t.sls_id,
    t.sls_nm,
    t.gsalesforce1_id,
    t.gsalesforce1_nm,
    t.gsalesforce2_id,
    t.gsalesforce2_nm,
    t.salesforce_id,
    t.salesforce_nm,
    t.salesforce_div_id,
    t.salesforce_div_nm,
    t.team_id,
    t.opr_type,
    t.cust_id,
    t.cust_nm,
    t.channel_id,
    t.channel_nm,
    t.group_channel_id,
    t.group_channel_nm,
    t.cycle_kunjungan,
    t.route,
    t.provinsi_code,
    t.provinsi_name,
    t.kabupaten_code,
    t.kabupaten_name,
    t.kecamatan_code,
    t.kecamatan_name,
    t.kelurahan_code,
    t.kelurahan_name,
    t.latitude,
    t.longitude,
    t.inv_no,
    t.pcode,
    t.pcode_nm,
    t.inv_qty,
    t.inv_val,
    t.qty_carton,
    t.product_gdiv_id,
    t.product_gdiv_nm,
    t.div_id,
    t.div_nm,
    t.product_team_id,
    t.product_team_nm,
    t.class_team_id,
    t.class_team_nm,
    t.subbrand_id,
    t.subbrand_nm,
    t.cat_id,
    t.cat_nm,
    t.sbu_id,
    t.sbu_nm,
    1                                     AS is_transaction
FROM {{ ref('silver_oa_transaction') }} t
